dictionary:
   ribbon:
      eureka:
         enabled: false
      listOfServers: od-api.oxforddictionaries.com:443
marvel:
  ribbon:
    eureka:
      enabled: false
    listOfServers: https://gateway.marvel.com:443
hr:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8080, localhost:9090
    ConnectTimeout: 250
    ReadTimeout: 5000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 2
server:
  port: 8080
