
object Versions {

    val projectVersion = "0.0.1-SNAPSHOT"
    val gradleVersion = "4.10.2"
    val kotlinVersion = "1.2.71"
    val kotlinTestVersion = "3.1.9"
    val mockitoKotlinVersion = "2.0.0-RC2"
    val kotlinLanguageVersion = "1.2"
    val kotlinApiVersion = "1.2"
    val kotlinJvmTarget = "1.8"
    val kotlinCoroutinesVersion = "0.25.0"
    val arrowVersion = "0.7.3"
    val findBugsVersion = "3.0.2"
    val junitVersion = "4.12"
    val detektVersion = "1.0.0.RC6-1"
    val materialDesignFontVersion = "1.7.22-4"
    val poiVersion = "3.17"
    val fuelVersion = "1.15.0"
    val rxKotlinVersion = "2.2.0"
    val tornadoFxVersion = "1.7.15"
    val httpClientVersion = "4.5.3"
    val controlsfxVersion = "8.40.14"
    val koinVersion = "0.9.1"
    val restAssuredVersion = "3.0.5"
    val lombokVersion = "1.14"
    val springBoot2Version = "2.0.0.RELEASE"
    val springBoot1Version = "1.5.16.RELEASE"
    val springDependencyManagementVersion = "1.0.6.RELEASE"
    val aopAlianceVersion = "1.0"
    val jacksonModuleKotlinVersion = "2.9.4.1"
}
